name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Build Release Files
        run: npm run build

      - uses: actions/upload-artifact@v3
        with:
          path: release/*.asar.gz
          if-no-files-found: ignore

  build-windows:
    runs-on: windows-latest
    needs: build
    steps:

      - uses: actions/upload-artifact@v3
        with:
          path: |
            release/*Setup*.exe
            release/*win.7z
          if-no-files-found: ignore

  build-mac:
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/upload-artifact@v3
        with:
          path: release/*-universal.dmg
          if-no-files-found: ignore

  build-linux:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/upload-artifact@v3
        with:
          path: release/*.AppImage
          if-no-files-found: ignore

  release:
    needs:
      - build-linux
      - build-mac
      - build-windows
    steps:
      - name: download-artifacts
        uses: actions/download-artifact@v3
        with:
          path: release

      - name: list all release files
        run: ls release

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*