name: Build
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Release Files
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - uses: actions/upload-artifact@v3
        with:
          name: upload-asar
          path: release/*.asar.gz
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v3
        with:
          name: upload-mac
          path: releae/*-universal.dmg
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v3
        with:
          name: upload-win
          path: |
            releae/*Setup*.exe
            releae/*win.7z
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v3
        with:
          name: upload-linux
          path: releae/*.AppImage
          if-no-files-found: ignore
